export type Category =
  | "salt-baked-chicken"
  | "pickled-mixed"
  | "dried-snacks"
  | "sauces-toppings"
  | "beverages";

export type MenuItem = {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: Category;
  tag?: string;
  trending?: boolean;
};

export const CATEGORIES: { id: Category; label: string; emoji: string }[] = [
  { id: "salt-baked-chicken", label: "Salt-Baked Chicken", emoji: "🍗" },
  { id: "pickled-mixed", label: "Pickled & Mixed", emoji: "🥗" },
  { id: "dried-snacks", label: "Dried Snacks", emoji: "🥨" },
  { id: "sauces-toppings", label: "Sauces & Toppings", emoji: "🌶️" },
  { id: "beverages", label: "Beverages", emoji: "🥤" },
];

export const MENU: MenuItem[] = [
  {
    id: "ga-1",
    name: "Whole Salt-Baked Ri Chicken (Grade 1)",
    description: "Premium whole chicken with firm meat and crispy skin.",
    price: 290,
    image: "/menu/ga-1.jpg",
    category: "salt-baked-chicken",
    tag: "Signature",
    trending: true,
  },
  {
    id: "ga-2",
    name: "Chopped Salt-Baked Ri Chicken",
    description: "Expertly chopped whole salt-baked chicken, ready to serve.",
    price: 290,
    image: "/menu/ga-2.jpg",
    category: "salt-baked-chicken",
  },
  {
    id: "ga-3",
    name: "Half Salt-Baked Ri Chicken",
    description: "A perfect half portion of our signature chicken.",
    price: 160,
    image: "/menu/ga-3.jpg",
    category: "salt-baked-chicken",
  },
  {
    id: "ngam-1s",
    name: "Pickled Beef Tendon (Small)",
    description: "Crunchy beef tendon in sweet and sour sauce.",
    price: 125,
    image: "/menu/ngam-1s.jpg",
    category: "pickled-mixed",
  },
  {
    id: "ngam-1l",
    name: "Pickled Beef Tendon (Large)",
    description: "Crunchy beef tendon in sweet and sour sauce.",
    price: 185,
    image: "/menu/ngam-1l.jpg",
    category: "pickled-mixed",
  },
  {
    id: "ngam-2",
    name: "Thai-Style Boneless Chicken Feet",
    description: "Boneless chicken feet in spicy Thai-style sauce.",
    price: 155,
    image: "/menu/ngam-2.jpg",
    category: "pickled-mixed",
    trending: true,
  },
  {
    id: "ngam-3",
    name: "Pig Ear & Beef Shank Roll",
    description: "Tender beef shank rolled with pig ear.",
    price: 195,
    image: "/menu/ngam-3.jpg",
    category: "pickled-mixed",
  },
  {
    id: "ngam-5",
    name: "Pickled Vegetables",
    description: "Mixed fresh vegetables pickled to perfection.",
    price: 110,
    image: "/menu/ngam-5.jpg",
    category: "pickled-mixed",
  },
  {
    id: "ngam-6l",
    name: "Mixed Tre Salad",
    description: "Traditional mixed Tre salad with herbs.",
    price: 110,
    image: "/menu/ngam-6.jpg",
    category: "pickled-mixed",
    trending: true,
  },
  {
    id: "ngam-8",
    name: "Mixed Tre Ingredient Combo",
    description: "Full ingredient set to mix your own Tre at home.",
    price: 300,
    image: "/menu/ngam-7.jpg",
    category: "pickled-mixed",
  },
  {
    id: "ngam-7",
    name: "Rice Paper with Dipping Sauce",
    description: "Includes five quail eggs and signature sauce.",
    price: 25,
    image: "/menu/kho-a.jpg",
    category: "dried-snacks",
  },
  {
    id: "kho-1a",
    name: "Soft-Dried Mango",
    description: "Traditional sweet and chewy dried mango.",
    price: 75,
    image: "/menu/kho-1a.jpg",
    category: "dried-snacks",
  },
  {
    id: "kho-2a",
    name: "Chili Salt Dried Mango",
    description: "Dried mango with a spicy chili-salt kick.",
    price: 85,
    image: "/menu/kho-2.jpg",
    category: "dried-snacks",
  },
  {
    id: "kho-3",
    name: "Crispy Fried Jackfruit (500g)",
    description: "Vacuum-fried crispy Thai jackfruit chips.",
    price: 165,
    image: "/menu/kho-3.jpg",
    category: "dried-snacks",
  },
  {
    id: "kho-4",
    name: "Rice Crackers with Pork Floss (250g)",
    description: "Traditional crunchy rice crackers.",
    price: 85,
    image: "/menu/kho-4.jpg",
    category: "dried-snacks",
  },
  {
    id: "kho-5",
    name: "Garlic Fish Sauce Pork Rind (200g)",
    description: "Crispy and flavorful pork rind snacks.",
    price: 115,
    image: "/menu/kho-5.jpg",
    category: "dried-snacks",
  },
  {
    id: "kho-6",
    name: "Premium Soft Beef Jerky (250g)",
    description: "High-quality soft and savory beef jerky.",
    price: 185,
    image: "/menu/kho-6.jpg",
    category: "dried-snacks",
    trending: true,
  },
  {
    id: "kho-7",
    name: "Shredded Chicken with Lime Leaves",
    description: "Flavorful chicken jerky in a 200g pack.",
    price: 95,
    image: "/menu/kho-7.jpg",
    category: "dried-snacks",
  },
  {
    id: "kho-8",
    name: "Premium Fish Sauce Pork Floss",
    description: "Salty and savory pork floss in a 200g pack.",
    price: 125,
    image: "/menu/kho-8.jpg",
    category: "dried-snacks",
  },
  {
    id: "kho-9",
    name: "Thick-Cut Soft-Dried Coconut",
    description: "Delicious dried coconut strips in a 500g pack.",
    price: 155,
    image: "/menu/kho-9.jpg",
    category: "dried-snacks",
  },
  {
    id: "kho-10",
    name: "Dew-Wetted Rice Paper Combo",
    description: "500g rice paper with shrimp salt and shallots.",
    price: 135,
    image: "/menu/kho-10.jpg",
    category: "dried-snacks",
  },
  {
    id: "gia-vi-2",
    name: "Steamed Fish Paste",
    description: "With salted egg and century egg.",
    price: 75,
    image: "/menu/gia-vi-2.jpg",
    category: "sauces-toppings",
  },
  {
    id: "gia-vi-3",
    name: "Divine Dipping Salt (250g)",
    description: "Our legendary signature dipping salt.",
    price: 85,
    image: "/menu/gia-vi-3.jpg",
    category: "sauces-toppings",
    tag: "Must Try",
  },
  {
    id: "top-1",
    name: "Pig Ear Tre Stick (Binh Dinh)",
    description: "Extra traditional Tre stick.",
    price: 30,
    image: "/menu/top-1.jpg",
    category: "sauces-toppings",
  },
  {
    id: "top-2",
    name: "Fermented Pork (Nem Chua)",
    description: "Extra portion of traditional nem chua.",
    price: 10,
    image: "/menu/top-2.jpg",
    category: "sauces-toppings",
  },
  {
    id: "top-3",
    name: "Pork Sausage Stick (Cha The)",
    description: "Traditional Vietnamese pork sausage.",
    price: 9,
    image: "/menu/top-3.jpg",
    category: "sauces-toppings",
  },
  {
    id: "top-4",
    name: "Spicy Beef Sausage with Tendon",
    description: "Flavorful beef sausage with chili.",
    price: 15,
    image: "/menu/top-4.jpg",
    category: "sauces-toppings",
  },
  {
    id: "top-5",
    name: "Extra Quail Eggs (5 pcs)",
    description: "Additional boiled quail eggs.",
    price: 10,
    image: "/menu/top-5.jpg",
    category: "sauces-toppings",
  },
  {
    id: "top-6",
    name: "Extra Shrimp Chips",
    description: "Crispy fried shrimp chips.",
    price: 5,
    image: "/menu/top-6.jpg",
    category: "sauces-toppings",
  },
  {
    id: "top-7",
    name: "Extra Fruits (Mango / Ambarella)",
    description: "Fresh seasonal fruit toppings.",
    price: 7,
    image: "https://aicdn.picsart.com/fd3b6585-b9b7-40f1-a752-7850642d1a22.jpg",
    category: "sauces-toppings",
  },
  {
    id: "nuoc-1",
    name: "Six-Flavor Herbal Coolant",
    description: "Refreshing traditional herbal tea.",
    price: 15,
    image: "/menu/nuoc-1.jpg",
    category: "beverages",
  },
  {
    id: "nuoc-2",
    name: "Soft Drink (Pepsi / 7Up / Sting)",
    description: "Chilled canned beverages.",
    price: 15,
    image: "/menu/nuoc-2.jpg",
    category: "beverages",
  },
  {
    id: "nuoc-3",
    name: "Bottled Water",
    description: "Pure mineral water.",
    price: 10,
    image: "/menu/nuoc-3.jpg",
    category: "beverages",
  },
  {
    id: "nuoc-4",
    name: "Wet Wipe",
    description: "Premium scented wet wipe.",
    price: 2,
    image: "/menu/nuoc-4.jpg",
    category: "beverages",
  },
];
